#!perl
use strict;
use warnings;

use AnyPAN::CLI::FileStorage;
AnyPAN::CLI::FileStorage->new_with_argv(@ARGV)->run();

__END__

=pod

=head1 NAME

anypan-merger - DarkPAN and CPAN mirror merging tool

=head1 SYNOPSIS

anypan-merger [options] [source_urls ...]

 Options:
   -h|--help                Brief help message
   -v|--verbose             Verbose log
   -o|--output-dir          Output directory (required)
   --with-packages          Writes also the packages included in the merged CPAN index
   --source-cache-dir       Source DarkPAN and CPAN mirror cache directory (default: /tmp/AnyPAN)
   --index-cache-timeout    Source DarkPAN and CPAN mirror index cache expiration seconds (default: 300s)
   --request-timeout        HTTP request timeout seconds (default: 30s)
   --max-retries            Max retry count
   --retry-interval         Retry interval
   --retry-jitter-factor    Retry jitter factor

=cut
