#!perl
use strict;
use warnings;

use CPAN::MirrorMerger::CLI::FileStorage;
CPAN::MirrorMerger::CLI::FileStorage->new_with_argv(@ARGV)->run();

__END__

=pod

=head1 NAME

cpan-mirror-merger - CPAN Mirror merge tool

=head1 SYNOPSIS

cpan-mirror-merger [options] [mirror_urls ...]

 Options:
   -h|--help                Brief help message
   -v|--verbose             Verbose log
   -o|--output-dir          Output directory (required)
   --mirror-cache-dir       Mirror cache directory (default: /tmp/CPAN-MirrorMerger)
   --index-cache-timeout    Mirror index cache timeout seconds (default: 300s)
   --request-timeout        HTTP request timeout seconds (default: 30s)
   --max-retries            Max retry count
   --retry-interval         Retry interval
   --retry-jitter-factor    Retry jitter factor

=cut
