name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - "5.32.0"
          - "5.30.3"
          - "5.28.3"
          - "5.26.3"
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: |
          cpanm --installdeps --with-develop --quiet --notest --skip-satisfied .
          perl Build.PL
          ./Build
          ./Build test
